spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  jackson:
    serialization:
      indent-output: true
server:
  ssl:
    key-store: ./keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: tomcat
    key-password: password
  port: 8443

